### ISSUE TITLE
"TypeError: callback is not a function" in /app/server.js:54

### ISSUE THREAD

**Issue by Pprime1** [Pprime1/csasm#31]
2021-12-06T07:17:59.292846+00:00 app[web.1]: Chosen Game is GCBETA : The Anti-Social-Mob cache: Beta test
2021-12-06T07:17:59.292906+00:00 app[web.1]: new game: GCBETA
2021-12-06T07:17:59.292984+00:00 app[web.1]: 5d6v0h1WT-dOhXF1AAAD joined game-GCBETA 1 online
2021-12-06T07:17:59.294927+00:00 app[web.1]: /app/server.js:54
2021-12-06T07:17:59.294929+00:00 app[web.1]:                 callback({ status: "Success", message: gamedesc });
2021-12-06T07:17:59.294930+00:00 app[web.1]:                 ^
2021-12-06T07:17:59.294930+00:00 app[web.1]: 
2021-12-06T07:17:59.294932+00:00 app[web.1]: TypeError: callback is not a function
2021-12-06T07:17:59.294932+00:00 app[web.1]:     at Socket.<anonymous> (/app/server.js:54:17)
2021-12-06T07:17:59.294932+00:00 app[web.1]:     at Socket.emit (events.js:400:28)
2021-12-06T07:17:59.294933+00:00 app[web.1]:     at Socket.emitUntyped (/app/node_modules/socket.io/dist/typed-events.js:69:22)
2021-12-06T07:17:59.294933+00:00 app[web.1]:     at /app/node_modules/socket.io/dist/socket.js:428:39
2021-12-06T07:17:59.294934+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:77:11)
2021-12-06T07:17:59.308100+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-12-06T07:17:59.308400+00:00 app[web.1]: npm ERR! errno 1
2021-12-06T07:17:59.315797+00:00 app[web.1]: npm ERR! csasm-nodejs@0.3.0 start: `node server.js`
2021-12-06T07:17:59.315885+00:00 app[web.1]: npm ERR! Exit status 1
2021-12-06T07:17:59.316060+00:00 app[web.1]: npm ERR! 
2021-12-06T07:17:59.316118+00:00 app[web.1]: npm ERR! Failed at the csasm-nodejs@0.3.0 start script.
2021-12-06T07:17:59.316189+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-12-06T07:17:59.322778+00:00 app[web.1]: 
2021-12-06T07:17:59.322925+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-12-06T07:17:59.322997+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-12-06T07_17_59_316Z-debug.log
2021-12-06T07:17:59.300992+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/socket.io/?EIO=4&transport=polling&t=NsEcq3V&sid=hm_ha5_rT69luoesAAAA" host=asmhub.herokuapp.com request_id=dfbd2182-7b90-4f44-aaf3-393009662342 fwd="49.182.59.76" dyno=web.1 connect=0ms service=23ms status=503 bytes=0 protocol=https
2021-12-06T07:17:59.300607+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=4&transport=websocket&sid=3UioBME-GskvmkGTAAAB" host=asmhub.herokuapp.com request_id=d8d25fd1-f9ab-4b7b-a7d3-663b785cf6b2 fwd="1.146.14.39" dyno=web.1 connect=0ms service=509ms status=101 bytes=129 protocol=https
2021-12-06T07:17:59.462712+00:00 heroku[web.1]: Process exited with status 1
2021-12-06T07:17:59.595771+00:00 heroku[web.1]: State changed from up to crashed

**Comment by Pprime1** [comment]
constant app crashes when in use by multiple players. Sample log above.

**Comment by Pprime1** [comment]
socket.on('join-a-game', (chosen_game, callback) => {
            // Start Chosen Game ...
            var game_details = getGameByCode(games_result, chosen_game);
            if(game_details != null) {  // Confirm game exists, a non null valid = successful game choice
                var gamedesc = game_details["description"];
                console.log("Chosen Game is", chosen_game, ":", gamedesc); 
		socket.join("game-" + chosen_game);
                callback({ status: "Success", message: gamedesc }); //WHY DOES THIS FAIL AND CRASH THE DYNO? CAN WE CATCH IT?
            } else {
		var game_error = "Invalid Game Code: " + chosen_game + " Please try again!"    
                callback({ status: "Error", message: game_error });  // Invalid game, leave form on screen with error message below
            };
        }); // join-a-game
    }); // on connection

**Comment by Pprime1** [comment]
Seems to crash more when a player session was running and the system restarts. So not "on connection" but "on reconnection". Is that relevant?

**Comment by Pprime1** [comment]
so there are three places the client can emit a 'join-a-game'. 
Firstly if a URL Parameter is provided. If it is not valid it rejects with an error and bounces down to the form.
Secondly, in the form - if no valid URL Parameter is provided (or none at all) it gets an entry from the form and tries that. If invalid, display an error and try again.
Thirdly - in the socket.io.on("reconnect") call .... I thought this wasn't being used, but clearly it is, when a client has previously connected but for some reason the server has forgotten, or restarted or something else has occurred. And the call there had NO callback response as you noted. Changed to ...
```
socket.io.on("reconnect", () => { // Reconnect if the client has dropped out for some reason but game was in progress
  if (is_joined) { 
      console.log(`RECONNECTING CLIENT ${current-game-id}`);
      socket.emit('join-a-game', $("#current-game-id").text(),(response) => {
        $("#game-error").text(response.message); // Set to display an error message underneath form entry field
      }); // emit join-a-game again
  };
});
```

will try and test this out

**Comment by judsona** [comment]
Yeah, it’ll likely occur when the player has closed down the browser (or paused. Which is how mobiles deal with it) 

when they reopen some time later it will attempt a reconnect

**Comment by Pprime1** [comment]
Put callback into the reconnect socket function
